"""initial_schema

Revision ID: f0e7573b9c1c
Revises: 
Create Date: 2026-07-25 00:02:54.268438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e7573b9c1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('index_review_queues_experiment_id'), table_name='review_queues')
    op.drop_table('review_queues')
    op.drop_index(op.f('ix_expectation_suites_contract_id'), table_name='expectation_suites')
    op.drop_index(op.f('ix_expectation_suites_created_at'), table_name='expectation_suites')
    op.drop_index(op.f('ix_expectation_suites_name'), table_name='expectation_suites')
    op.drop_index(op.f('ix_expectation_suites_status'), table_name='expectation_suites')
    op.drop_table('expectation_suites')
    op.drop_index(op.f('index_logged_model_metrics_model_id'), table_name='logged_model_metrics')
    op.drop_table('logged_model_metrics')
    op.drop_index(op.f('index_review_queue_users_user_id'), table_name='review_queue_users')
    op.drop_table('review_queue_users')
    op.drop_index(op.f('index_scorer_versions_scorer_id'), table_name='scorer_versions')
    op.drop_table('scorer_versions')
    op.drop_index(op.f('idx_guardrails_scorer'), table_name='guardrails')
    op.drop_index(op.f('idx_guardrails_workspace'), table_name='guardrails')
    op.drop_table('guardrails')
    op.drop_table('logged_model_params')
    op.drop_index(op.f('idx_secrets_workspace'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('index_review_queue_label_schemas_schema_id'), table_name='review_queue_label_schemas')
    op.drop_table('review_queue_label_schemas')
    op.drop_index(op.f('index_endpoint_model_mappings_endpoint_id'), table_name='endpoint_model_mappings')
    op.drop_index(op.f('index_endpoint_model_mappings_model_definition_id'), table_name='endpoint_model_mappings')
    op.drop_index(op.f('unique_endpoint_model_linkage_mapping'), table_name='endpoint_model_mappings')
    op.drop_table('endpoint_model_mappings')
    op.drop_index(op.f('index_trace_info_experiment_id_timestamp_ms'), table_name='trace_info')
    op.drop_table('trace_info')
    op.drop_index(op.f('index_jobs_name_status_creation_time'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('online_scoring_configs')
    op.drop_index(op.f('index_trace_tags_request_id'), table_name='trace_tags')
    op.drop_table('trace_tags')
    op.drop_index(op.f('index_trace_request_metadata_request_id'), table_name='trace_request_metadata')
    op.drop_table('trace_request_metadata')
    op.drop_index(op.f('idx_budget_policies_workspace'), table_name='budget_policies')
    op.drop_table('budget_policies')
    op.drop_index(op.f('idx_endpoints_workspace'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('index_endpoint_tags_endpoint_id'), table_name='endpoint_tags')
    op.drop_table('endpoint_tags')
    op.drop_index(op.f('ix_validation_replay_jobs_created_at'), table_name='validation_replay_jobs')
    op.drop_index(op.f('ix_validation_replay_jobs_dataset_version_id'), table_name='validation_replay_jobs')
    op.drop_index(op.f('ix_validation_replay_jobs_status'), table_name='validation_replay_jobs')
    op.drop_index(op.f('ix_validation_replay_jobs_suite_id'), table_name='validation_replay_jobs')
    op.drop_table('validation_replay_jobs')
    op.drop_index(op.f('index_issues_experiment_id'), table_name='issues')
    op.drop_index(op.f('index_issues_source_run_id'), table_name='issues')
    op.drop_index(op.f('index_issues_status'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('index_review_queue_items_item_id'), table_name='review_queue_items')
    op.drop_index(op.f('index_review_queue_items_queue_id_status'), table_name='review_queue_items')
    op.drop_table('review_queue_items')
    op.drop_index(op.f('idx_model_definitions_workspace'), table_name='model_definitions')
    op.drop_index(op.f('index_model_definitions_provider'), table_name='model_definitions')
    op.drop_index(op.f('index_model_definitions_secret_id'), table_name='model_definitions')
    op.drop_table('model_definitions')
    op.drop_index(op.f('index_scorers_experiment_id_scorer_name'), table_name='scorers')
    op.drop_table('scorers')
    op.drop_index(op.f('ix_validation_runs_created_at'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_dataset_version_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_pipeline_run_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_suite_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('index_label_schemas_experiment_id'), table_name='label_schemas')
    op.drop_table('label_schemas')
    op.drop_index(op.f('idx_webhook_events_action'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_events_entity'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_events_entity_action'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('index_trace_metrics_request_id'), table_name='trace_metrics')
    op.drop_table('trace_metrics')
    op.drop_index(op.f('index_spans_experiment_id'), table_name='spans')
    op.drop_index(op.f('index_spans_experiment_id_duration'), table_name='spans')
    op.drop_index(op.f('index_spans_experiment_id_status_type'), table_name='spans')
    op.drop_index(op.f('index_spans_experiment_id_type_status'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('idx_webhooks_name'), table_name='webhooks')
    op.drop_index(op.f('idx_webhooks_status'), table_name='webhooks')
    op.drop_index(op.f('idx_webhooks_workspace'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_table('endpoint_bindings')
    op.drop_index(op.f('ix_data_contracts_created_at'), table_name='data_contracts')
    op.drop_index(op.f('ix_data_contracts_dataset_name'), table_name='data_contracts')
    op.drop_index(op.f('ix_data_contracts_status'), table_name='data_contracts')
    op.drop_table('data_contracts')
    op.drop_index(op.f('idx_evaluation_datasets_workspace'), table_name='evaluation_datasets')
    op.drop_index(op.f('index_evaluation_datasets_created_time'), table_name='evaluation_datasets')
    op.drop_index(op.f('index_evaluation_datasets_name'), table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    op.drop_index(op.f('index_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('index_assessments_last_updated_timestamp'), table_name='assessments')
    op.drop_index(op.f('index_assessments_run_id_created_timestamp'), table_name='assessments')
    op.drop_index(op.f('index_assessments_trace_id_created_timestamp'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('logged_models')
    op.drop_table('workspaces')
    op.drop_index(op.f('idx_guardrail_configs_endpoint_id'), table_name='guardrail_configs')
    op.drop_index(op.f('idx_guardrail_configs_guardrail_id'), table_name='guardrail_configs')
    op.drop_table('guardrail_configs')
    op.drop_table('logged_model_tags')
    op.drop_index(op.f('index_evaluation_dataset_tags_dataset_id'), table_name='evaluation_dataset_tags')
    op.drop_table('evaluation_dataset_tags')
    op.drop_index(op.f('index_span_metrics_trace_id_span_id'), table_name='span_metrics')
    op.drop_table('span_metrics')
    op.drop_index(op.f('ix_expectation_results_expectation_type'), table_name='expectation_results')
    op.drop_index(op.f('ix_expectation_results_severity'), table_name='expectation_results')
    op.drop_index(op.f('ix_expectation_results_validation_run_id'), table_name='expectation_results')
    op.drop_table('expectation_results')
    op.drop_index(op.f('index_entity_associations_association_id'), table_name='entity_associations')
    op.drop_index(op.f('index_entity_associations_reverse_lookup'), table_name='entity_associations')
    op.drop_table('entity_associations')
    op.drop_index(op.f('index_evaluation_dataset_records_dataset_id'), table_name='evaluation_dataset_records')
    op.drop_table('evaluation_dataset_records')
    op.create_foreign_key(None, 'drift_reports', 'model_versions', ['model_version_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_experiments_mlflow_experiment_id'), 'experiments', ['mlflow_experiment_id'], unique=False)
    op.create_index(op.f('ix_experiments_mlflow_run_id'), 'experiments', ['mlflow_run_id'], unique=False)
    op.create_index(op.f('ix_experiments_model_name'), 'experiments', ['model_name'], unique=False)
    op.create_foreign_key(None, 'inference_requests', 'model_versions', ['model_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'model_artifacts', 'model_versions', ['model_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'predictions', 'model_versions', ['model_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_metrics', 'model_versions', ['model_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_metrics', type_='foreignkey')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_constraint(None, 'model_artifacts', type_='foreignkey')
    op.drop_constraint(None, 'inference_requests', type_='foreignkey')
    op.drop_index(op.f('ix_experiments_model_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_mlflow_run_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_mlflow_experiment_id'), table_name='experiments')
    op.drop_constraint(None, 'drift_reports', type_='foreignkey')
    op.create_table('evaluation_dataset_records',
    sa.Column('dataset_record_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expectations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('input_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.dataset_id'], name=op.f('fk_evaluation_dataset_records_dataset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_record_id', name=op.f('evaluation_dataset_records_pk')),
    sa.UniqueConstraint('dataset_id', 'input_hash', name=op.f('unique_dataset_input'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('index_evaluation_dataset_records_dataset_id'), 'evaluation_dataset_records', ['dataset_id'], unique=False)
    op.create_table('entity_associations',
    sa.Column('association_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_type', 'source_id', 'destination_type', 'destination_id', name=op.f('entity_associations_pk'))
    )
    op.create_index(op.f('index_entity_associations_reverse_lookup'), 'entity_associations', ['destination_type', 'destination_id', 'source_type', 'source_id'], unique=False)
    op.create_index(op.f('index_entity_associations_association_id'), 'entity_associations', ['association_id'], unique=False)
    op.create_table('expectation_results',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('validation_run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expectation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('observed_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exception_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('expectation_results_validation_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('expectation_results_pkey'))
    )
    op.create_index(op.f('ix_expectation_results_validation_run_id'), 'expectation_results', ['validation_run_id'], unique=False)
    op.create_index(op.f('ix_expectation_results_severity'), 'expectation_results', ['severity'], unique=False)
    op.create_index(op.f('ix_expectation_results_expectation_type'), 'expectation_results', ['expectation_type'], unique=False)
    op.create_table('span_metrics',
    sa.Column('trace_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('span_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trace_id', 'span_id'], ['spans.trace_id', 'spans.span_id'], name=op.f('fk_span_metrics_span'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id', 'span_id', 'key', name=op.f('span_metrics_pk'))
    )
    op.create_index(op.f('index_span_metrics_trace_id_span_id'), 'span_metrics', ['trace_id', 'span_id'], unique=False)
    op.create_table('evaluation_dataset_tags',
    sa.Column('dataset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.dataset_id'], name=op.f('fk_evaluation_dataset_tags_dataset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'key', name=op.f('evaluation_dataset_tags_pk'))
    )
    op.create_index(op.f('index_evaluation_dataset_tags_dataset_id'), 'evaluation_dataset_tags', ['dataset_id'], unique=False)
    op.create_table('logged_model_tags',
    sa.Column('model_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tag_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['logged_models.model_id'], name=op.f('fk_logged_model_tags_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'tag_key', name=op.f('logged_model_tags_pk'))
    )
    op.create_table('guardrail_configs',
    sa.Column('endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('guardrail_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('execution_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], name=op.f('fk_guardrail_configs_endpoint_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardrail_id'], ['guardrails.guardrail_id'], name=op.f('fk_guardrail_configs_guardrail_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_id', 'guardrail_id', name=op.f('guardrail_configs_pk'))
    )
    op.create_index(op.f('idx_guardrail_configs_guardrail_id'), 'guardrail_configs', ['guardrail_id'], unique=False)
    op.create_index(op.f('idx_guardrail_configs_endpoint_id'), 'guardrail_configs', ['endpoint_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_artifact_root', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trace_archival_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trace_archival_retention', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('workspaces_pk'))
    )
    op.create_table('logged_models',
    sa.Column('model_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('artifact_location', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('creation_timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('model_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source_run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name=op.f('logged_models_lifecycle_stage_check')),
    sa.PrimaryKeyConstraint('model_id', name=op.f('logged_models_pk'))
    )
    op.create_table('assessments',
    sa.Column('assessment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('assessment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('span_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overrides', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('assessment_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['trace_info.request_id'], name=op.f('fk_assessments_trace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('assessments_pk'))
    )
    op.create_index(op.f('index_assessments_trace_id_created_timestamp'), 'assessments', ['trace_id', 'created_timestamp'], unique=False)
    op.create_index(op.f('index_assessments_run_id_created_timestamp'), 'assessments', ['run_id', 'created_timestamp'], unique=False)
    op.create_index(op.f('index_assessments_last_updated_timestamp'), 'assessments', ['last_updated_timestamp'], unique=False)
    op.create_index(op.f('index_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_table('evaluation_datasets',
    sa.Column('dataset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('digest', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('dataset_id', name=op.f('evaluation_datasets_pk'))
    )
    op.create_index(op.f('index_evaluation_datasets_name'), 'evaluation_datasets', ['name'], unique=False)
    op.create_index(op.f('index_evaluation_datasets_created_time'), 'evaluation_datasets', ['created_time'], unique=False)
    op.create_index(op.f('idx_evaluation_datasets_workspace'), 'evaluation_datasets', ['workspace'], unique=False)
    op.create_table('data_contracts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataset_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('schema_definition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('business_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('primary_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_contracts_pkey')),
    sa.UniqueConstraint('dataset_name', 'version', name=op.f('uq_contract_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_data_contracts_status'), 'data_contracts', ['status'], unique=False)
    op.create_index(op.f('ix_data_contracts_dataset_name'), 'data_contracts', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_data_contracts_created_at'), 'data_contracts', ['created_at'], unique=False)
    op.create_table('endpoint_bindings',
    sa.Column('endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], name=op.f('fk_endpoint_bindings_endpoint_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_id', 'resource_type', 'resource_id', name=op.f('endpoint_bindings_pk'))
    )
    op.create_table('webhooks',
    sa.Column('webhook_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('creation_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('deleted_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('webhook_id', name=op.f('webhook_pk'))
    )
    op.create_index(op.f('idx_webhooks_workspace'), 'webhooks', ['workspace'], unique=False)
    op.create_index(op.f('idx_webhooks_status'), 'webhooks', ['status'], unique=False)
    op.create_index(op.f('idx_webhooks_name'), 'webhooks', ['name'], unique=False)
    op.create_table('spans',
    sa.Column('trace_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('span_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parent_span_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time_unix_nano', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_time_unix_nano', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('duration_ns', sa.BIGINT(), sa.Computed('(end_time_unix_nano - start_time_unix_nano)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dimension_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['trace_info.request_id'], name=op.f('fk_spans_trace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id', 'span_id', name=op.f('spans_pk'))
    )
    op.create_index(op.f('index_spans_experiment_id_type_status'), 'spans', ['experiment_id', 'type', 'status'], unique=False)
    op.create_index(op.f('index_spans_experiment_id_status_type'), 'spans', ['experiment_id', 'status', 'type'], unique=False)
    op.create_index(op.f('index_spans_experiment_id_duration'), 'spans', ['experiment_id', 'duration_ns'], unique=False)
    op.create_index(op.f('index_spans_experiment_id'), 'spans', ['experiment_id'], unique=False)
    op.create_table('trace_metrics',
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name=op.f('fk_trace_metrics_request_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'key', name=op.f('trace_metrics_pk'))
    )
    op.create_index(op.f('index_trace_metrics_request_id'), 'trace_metrics', ['request_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('webhook_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.webhook_id'], name=op.f('webhook_events_webhook_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('webhook_id', 'entity', 'action', name=op.f('webhook_event_pk'))
    )
    op.create_index(op.f('idx_webhook_events_entity_action'), 'webhook_events', ['entity', 'action'], unique=False)
    op.create_index(op.f('idx_webhook_events_entity'), 'webhook_events', ['entity'], unique=False)
    op.create_index(op.f('idx_webhook_events_action'), 'webhook_events', ['action'], unique=False)
    op.create_table('label_schemas',
    sa.Column('schema_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('instruction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enable_comment', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('input_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('input_config', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('schema_id', name=op.f('label_schemas_pk')),
    sa.UniqueConstraint('experiment_id', 'name', name=op.f('uq_label_schemas_exp_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('index_label_schemas_experiment_id'), 'label_schemas', ['experiment_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('suite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataset_version_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('critical_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warning_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('info_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gx_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dataset_checksum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('validation_runs_dataset_version_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('validation_runs_pipeline_run_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_id'], ['expectation_suites.id'], name=op.f('validation_runs_suite_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_runs_pkey'))
    )
    op.create_index(op.f('ix_validation_runs_suite_id'), 'validation_runs', ['suite_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_pipeline_run_id'), 'validation_runs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_dataset_version_id'), 'validation_runs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_created_at'), 'validation_runs', ['created_at'], unique=False)
    op.create_table('scorers',
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scorer_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('scorer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('scorer_id', name=op.f('scorer_pk'))
    )
    op.create_index(op.f('index_scorers_experiment_id_scorer_name'), 'scorers', ['experiment_id', 'scorer_name'], unique=True)
    op.create_table('model_definitions',
    sa.Column('model_definition_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('secret_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.secret_id'], name=op.f('fk_model_definitions_secret_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('model_definition_id', name=op.f('model_definitions_pk')),
    sa.UniqueConstraint('workspace', 'name', name=op.f('uq_model_definitions_workspace_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('index_model_definitions_secret_id'), 'model_definitions', ['secret_id'], unique=False)
    op.create_index(op.f('index_model_definitions_provider'), 'model_definitions', ['provider'], unique=False)
    op.create_index(op.f('idx_model_definitions_workspace'), 'model_definitions', ['workspace'], unique=False)
    op.create_table('review_queue_items',
    sa.Column('queue_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('completed_by', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('completed_time_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('creation_time_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_update_time_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['review_queues.queue_id'], name=op.f('fk_review_queue_items_queue_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id', 'item_id', name=op.f('review_queue_items_pk'))
    )
    op.create_index(op.f('index_review_queue_items_queue_id_status'), 'review_queue_items', ['queue_id', 'status'], unique=False)
    op.create_index(op.f('index_review_queue_items_item_id'), 'review_queue_items', ['item_id'], unique=False)
    op.create_table('issues',
    sa.Column('issue_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('root_causes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('categories', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('issue_id', name=op.f('issues_pk'))
    )
    op.create_index(op.f('index_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('index_issues_source_run_id'), 'issues', ['source_run_id'], unique=False)
    op.create_index(op.f('index_issues_experiment_id'), 'issues', ['experiment_id'], unique=False)
    op.create_table('validation_replay_jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataset_version_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('suite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_validation_run_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('validation_replay_jobs_dataset_version_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_validation_run_id'], ['validation_runs.id'], name=op.f('validation_replay_jobs_result_validation_run_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_id'], ['expectation_suites.id'], name=op.f('validation_replay_jobs_suite_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_replay_jobs_pkey'))
    )
    op.create_index(op.f('ix_validation_replay_jobs_suite_id'), 'validation_replay_jobs', ['suite_id'], unique=False)
    op.create_index(op.f('ix_validation_replay_jobs_status'), 'validation_replay_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_validation_replay_jobs_dataset_version_id'), 'validation_replay_jobs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_validation_replay_jobs_created_at'), 'validation_replay_jobs', ['created_at'], unique=False)
    op.create_table('endpoint_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], name=op.f('fk_endpoint_tags_endpoint_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'endpoint_id', name=op.f('endpoint_tag_pk'))
    )
    op.create_index(op.f('index_endpoint_tags_endpoint_id'), 'endpoint_tags', ['endpoint_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('routing_strategy', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('fallback_config_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usage_tracking', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('endpoint_id', name=op.f('endpoints_pk')),
    sa.UniqueConstraint('workspace', 'name', name=op.f('uq_endpoints_workspace_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_endpoints_workspace'), 'endpoints', ['workspace'], unique=False)
    op.create_table('budget_policies',
    sa.Column('budget_policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('budget_unit', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('budget_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('duration_unit', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('duration_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_scope', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('budget_action', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('budget_policy_id', name=op.f('budget_policies_pk'))
    )
    op.create_index(op.f('idx_budget_policies_workspace'), 'budget_policies', ['workspace'], unique=False)
    op.create_table('trace_request_metadata',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name=op.f('fk_trace_request_metadata_request_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'request_id', name=op.f('trace_request_metadata_pk'))
    )
    op.create_index(op.f('index_trace_request_metadata_request_id'), 'trace_request_metadata', ['request_id'], unique=False)
    op.create_table('trace_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name=op.f('fk_trace_tags_request_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'request_id', name=op.f('trace_tag_pk'))
    )
    op.create_index(op.f('index_trace_tags_request_id'), 'trace_tags', ['request_id'], unique=False)
    op.create_table('online_scoring_configs',
    sa.Column('online_scoring_config_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scorer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sample_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filter_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scorer_id'], ['scorers.scorer_id'], name=op.f('fk_online_scoring_configs_scorer_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('online_scoring_config_id', name=op.f('online_scoring_config_pk'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('params', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pk'))
    )
    op.create_index(op.f('index_jobs_name_status_creation_time'), 'jobs', ['job_name', 'workspace', 'status', 'creation_time'], unique=False)
    op.create_table('trace_info',
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('execution_time_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('client_request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('request_preview', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('response_preview', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('db_payload_generation', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('request_id', name=op.f('trace_info_pk'))
    )
    op.create_index(op.f('index_trace_info_experiment_id_timestamp_ms'), 'trace_info', ['experiment_id', 'timestamp_ms'], unique=False)
    op.create_table('endpoint_model_mappings',
    sa.Column('mapping_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('model_definition_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('linkage_type', sa.VARCHAR(length=64), server_default=sa.text("'PRIMARY'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fallback_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], name=op.f('fk_endpoint_model_mappings_endpoint_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_definition_id'], ['model_definitions.model_definition_id'], name=op.f('fk_endpoint_model_mappings_model_definition_id')),
    sa.PrimaryKeyConstraint('mapping_id', name=op.f('endpoint_model_mappings_pk'))
    )
    op.create_index(op.f('unique_endpoint_model_linkage_mapping'), 'endpoint_model_mappings', ['endpoint_id', 'model_definition_id', 'linkage_type'], unique=True)
    op.create_index(op.f('index_endpoint_model_mappings_model_definition_id'), 'endpoint_model_mappings', ['model_definition_id'], unique=False)
    op.create_index(op.f('index_endpoint_model_mappings_endpoint_id'), 'endpoint_model_mappings', ['endpoint_id'], unique=False)
    op.create_table('review_queue_label_schemas',
    sa.Column('queue_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('schema_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['review_queues.queue_id'], name=op.f('fk_review_queue_label_schemas_queue_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id', 'schema_id', name=op.f('review_queue_label_schemas_pk'))
    )
    op.create_index(op.f('index_review_queue_label_schemas_schema_id'), 'review_queue_label_schemas', ['schema_id'], unique=False)
    op.create_table('secrets',
    sa.Column('secret_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('encrypted_value', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('wrapped_dek', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('kek_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('masked_value', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('auth_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('secret_id', name=op.f('secrets_pk')),
    sa.UniqueConstraint('workspace', 'secret_name', name=op.f('uq_secrets_workspace_secret_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_secrets_workspace'), 'secrets', ['workspace'], unique=False)
    op.create_table('logged_model_params',
    sa.Column('model_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('param_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('param_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['logged_models.model_id'], name=op.f('fk_logged_model_params_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'param_key', name=op.f('logged_model_params_pk'))
    )
    op.create_table('guardrails',
    sa.Column('guardrail_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scorer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scorer_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('action_endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=63), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_endpoint_id'], ['endpoints.endpoint_id'], name=op.f('fk_guardrails_action_endpoint_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scorer_id', 'scorer_version'], ['scorer_versions.scorer_id', 'scorer_versions.scorer_version'], name=op.f('fk_guardrails_scorer_version')),
    sa.PrimaryKeyConstraint('guardrail_id', name=op.f('guardrails_pk'))
    )
    op.create_index(op.f('idx_guardrails_workspace'), 'guardrails', ['workspace'], unique=False)
    op.create_index(op.f('idx_guardrails_scorer'), 'guardrails', ['scorer_id', 'scorer_version'], unique=False)
    op.create_table('scorer_versions',
    sa.Column('scorer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scorer_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serialized_scorer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scorer_id'], ['scorers.scorer_id'], name=op.f('fk_scorer_versions_scorer_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scorer_id', 'scorer_version', name=op.f('scorer_version_pk'))
    )
    op.create_index(op.f('index_scorer_versions_scorer_id'), 'scorer_versions', ['scorer_id'], unique=False)
    op.create_table('review_queue_users',
    sa.Column('queue_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['review_queues.queue_id'], name=op.f('fk_review_queue_users_queue_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id', 'user_id', name=op.f('review_queue_users_pk'))
    )
    op.create_index(op.f('index_review_queue_users_user_id'), 'review_queue_users', ['user_id'], unique=False)
    op.create_table('logged_model_metrics',
    sa.Column('model_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('metric_timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('metric_step', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('dataset_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('dataset_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('dataset_digest', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['logged_models.model_id'], name=op.f('fk_logged_model_metrics_model_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'metric_name', 'metric_timestamp_ms', 'metric_step', 'run_id', name=op.f('logged_model_metrics_pk'))
    )
    op.create_index(op.f('index_logged_model_metrics_model_id'), 'logged_model_metrics', ['model_id'], unique=False)
    op.create_table('expectation_suites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('suite_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expectation_configs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['data_contracts.id'], name=op.f('expectation_suites_contract_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('expectation_suites_pkey'))
    )
    op.create_index(op.f('ix_expectation_suites_status'), 'expectation_suites', ['status'], unique=False)
    op.create_index(op.f('ix_expectation_suites_name'), 'expectation_suites', ['name'], unique=False)
    op.create_index(op.f('ix_expectation_suites_created_at'), 'expectation_suites', ['created_at'], unique=False)
    op.create_index(op.f('ix_expectation_suites_contract_id'), 'expectation_suites', ['contract_id'], unique=False)
    op.create_table('review_queues',
    sa.Column('queue_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('queue_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creation_time_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_update_time_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name_key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('queue_id', name=op.f('review_queues_pk')),
    sa.UniqueConstraint('experiment_id', 'name_key', name=op.f('uq_review_queues_experiment_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('index_review_queues_experiment_id'), 'review_queues', ['experiment_id'], unique=False)
    # ### end Alembic commands ###
